### ISSUE TITLE
Passing multiple short options is not working

### ISSUE THREAD

**Issue by igorsantos07** [c9s/GetOptionKit#12]
If I have multiple short options in my command and I pass them like `-mv` I'll just get the first one as a passed option. Using `-l -v` works.

Also, using `-vm4` does the same, while it should give me the `v` option as boolean, and `m` as `4`. Doing `-m4v` gives me `m` without the value as well, and nothing else.

**Comment by c9s** [comment]
This works on dev-master, retry again? I will close this issue, if you still encounter this problem, please re-open it again. Thanks!

You can try it with:

```sh
php examples/demo.php -mvvs
```

And it shall output:

```
Enabled options:
* key:output   spec:-o, --output[=<File:output.txt>]  desc:option with optional value.
  value => output.txt

* key:m        spec:-m  desc:short option m
  value => 1

* key:verbose  spec:-v, --verbose  desc:verbose
  value => 2

* key:s        spec:-s  desc:short option name only.
  value => 1
```

**Comment by c9s** [comment]
PS. `php examples/demo.php -mv4` works for me. :)

**Comment by igorsantos07** [comment]
Well, it makes a whole lot of sense. In the end, the bug is more than a year old, right? It should be a bug in those 1.2.* releases that got fixed in this year of development.

I'll have some trouble updating my dependencies to catch up the novelties, but I guess the bug is dead anyway.

**Comment by c9s** [comment]
Well, when I tested the issue you reported, it's already been fixed (maybe it's fixed by other's PR)

And after the new release got released, I went back to review the issue you report and it seems already fixed. :)

**Comment by c9s** [comment]
If you have any problem while you're upgrading your dependencies, just fire me an issue, I will help you to get rid of these problems.

**Comment by igorsantos07** [comment]
Ok, thanks!

Is there any changelog on the breaking changes between 1.* and 2.* for this
repository and the CLI Framework?

*Igor Santos*
Desenvolvedor web / mobile
igorsantos.com.br <http://www.igorsantos.com.br>

**Comment by c9s** [comment]
No, but i can review it and update the changelog for you

**Comment by igorsantos07** [comment]
That's kind of you :)

It's adviseable to include breaking changes when you update the major
version of a package. If you want to do it only because of my upgrade, hold
it. When I update the packages, if stuff break, I'll tell you and you
update the changelogs. Ok?
So there's no time wasted.

*Igor Santos*
Desenvolvedor web / mobile
igorsantos.com.br <http://www.igorsantos.com.br>

**Comment by c9s** [comment]
OK, Thanks!
