### ISSUE TITLE
Can not enter negative numbers

### ISSUE THREAD

**Issue by vasek125** [c9s/GetOptionKit#21]
If number begins with -, it is treated as an option. Current workaround: use something like: -o " -1" because -o "-1" will not work.

**Comment by c9s** [comment]
Looks like the logic needs to be fixed in the below flow:

- see if `-1` option exists
- if not, check the previous option `-o` requires a value?
- if `-o` requires a value, pass `-1` value to `-o` option.

**Comment by Gasol** [comment]
reasonable

**Comment by c9s** [comment]
Hi @Gasol , @vasek125    I just fixed it, give it a try with dev-master ?

**Comment by Gasol** [comment]
Looks good to me.

**Comment by c9s** [comment]
OK I will release this changes in the next minor version.

**Comment by Gasol** [comment]
@c9s I think next minor version should also change autoload from psr-0 to psr-4, Because psr-0 is deprecated.

**Comment by c9s** [comment]
sure :)

**Comment by Gasol** [comment]
:+1:

**Comment by c9s** [comment]
Updated and Released!

**Comment by c9s** [comment]
I am closing. :)
