### ISSUE TITLE
Fatal error: Call to a member function isOption() on null

### ISSUE THREAD

**Issue by 1Franck** [c9s/GetOptionKit#27]
spec option with multiple values output fatal error when value(s) missing

```php
...
$specs->add('b|bar+', 'option with multiple value.' )->isa('Number');
...
```
$ php script.php -f foo -b

Fatal error: Call to a member function isOption() on null in ...\vendor\corneltek\getoptionkit\src\GetOptionKit\OptionParser.php on line 187

$ php script.php -f foo -b 1 -b 2
  Array
(
    [0] => 1
    [1] => 2
)

OptionParser.php temp fix
```php
if($next) {
    if($next->isOption())
        $i++;
    $result->set($spec->getId(), $spec);
}
```

**Comment by c9s** [comment]
Released in 2.1.1
