### ISSUE TITLE
[BUG] ContinuousOptionParser fail to parse multiple  --option=value

### ISSUE THREAD

**Issue by jeffreycahyono** [c9s/GetOptionKit#36]
Please test using this command, it will fail

```php
"script.php subcommand --data=thedata --limit=30 --batch=10 --index=theindex argument1 argument2"
```
The parser only parse data, limit, and batch, and ignoring the rest (index, argument1, argument2 is not  parsed

**Comment by c9s** [comment]
Can you provide the option spec you used? thanks

jeffreycahyono <notifications@github.com> 於 2015年9月17日 星期四寫道：

**Comment by jeffreycahyono** [comment]
```php
    /**
     * Generate options spec
     * @return \GetOptionKit\OptionCollection
     */
    private function getTaskOptionSpec()
    {
        $spec = new OptionCollection();
        $spec->add('d|data:=string', 'data state file path (required)');
        $spec->add('l|limit:=number', 'max number of records fetched, default: no limit');
        $spec->add('b|batch:=number', 'number of records batched, default: 1000');
        $spec->add('index:=string', 'Name of index, default: system deterimined');
        return $spec;
    }
```

**Comment by c9s** [comment]
Ok I will check that latet

jeffreycahyono <notifications@github.com> 於 2015年9月17日 星期四寫道：

**Comment by jeffreycahyono** [comment]
I've debug, the problem is in 

https://github.com/c9s/GetOptionKit/blob/1cae3b6915b277704e749cf1574df374f6be376e/src/GetOptionKit/ContinuousOptionParser.php#L133

```preprocessingArguments()``` changes ```$argv[8]``` to $argv[12]```, but ```$this->length``` is still 8

**Comment by c9s** [comment]
But you only have 8 Argugments, isn't?

jeffreycahyono <notifications@github.com> 於 2015年9月17日 星期四寫道：

**Comment by c9s** [comment]
check out CLIFramework there is an example of using continuous parser

Yo-An Lin <yoanlin93@gmail.com> 於 2015年9月17日 星期四寫道：

**Comment by jeffreycahyono** [comment]
No 12.
Your library works fine when the input is
```
"script.php subcommand --data thedata --limit 30 --batch 10 --index theindex argument1 argument2"
```
Because argv already [12] and  preprocessingArguments will not modify argv

But when using ```=``` (equal sign) it will fail

**Comment by jeffreycahyono** [comment]
Sorry, I'm not following your CLIFramework, but I'm sure  this is a bug. Please include it to your testcase.

The result of these commands should be the same right? 

The first:
```
"script.php subcommand --data thedata --limit 30 --batch 10 --index theindex argument1 argument2"
```
The second:
```
"script.php subcommand --data=thedata --limit=30 --batch=10 --index=theindex argument1 argument2"
```

**Comment by c9s** [comment]
Sure

jeffreycahyono <notifications@github.com> 於 2015年9月17日 星期四寫道：

**Comment by jeffreycahyono** [comment]
The fact, the second, would fail

**Comment by jeffreycahyono** [comment]
```php
public function testTaskOpts()
{

	$cmd = explode(
		' ',
		'program perintah --data=thedata --limit=30 --batch=10 --index=theindex argument1 argument2'
	);
	$appSpecs = new OptionCollection();
	
	$p = new ContinuousOptionParser($appSpecs);
	$appOptions = $parser->parse($arguments);
	$taskName = $p->getCurrentArgument();
	$p->advance();
	$this->assertEquals('perintah', $taskName);
	
	
	$specs = $this->getTaskOptionSpec();
	$p->setSpecs($specs);
	$options = $p->continueParse();
	$params = [];
	while (!$p->isEnd()) {
		$params[] = $p->advance();
	}

	$this->assertSame('thedata', $taskOpts->data);
	$this->assertSame(30, $taskOpts->limit);
	$this->assertSame(10, $taskOpts->batch);
	$this->assertSame('theindex', $taskOpts->index);
	$this->assertEquals(['argument1', 'argument2'], $params);
}
```

**Comment by jeffreycahyono** [comment]
Hi Yo-An Lin, any update for this issue?

**Comment by c9s** [comment]
That's weird, please check out the following test case, it's passing:

https://github.com/c9s/GetOptionKit/blob/master/tests/GetOptionKit/ContinuousOptionParserTest.php#L96

**Comment by c9s** [comment]
ContinousOptionParser will *stop* at a non-option token, usually subcommand name. you should call `continueParse()` when your parser meets subcommand name tokens.

**Comment by c9s** [comment]
So your code:

```
while (!$p->isEnd()) {
        $params[] = $p->advance();
    }
```

Just push the following options to arguments. you didn't call `continueParse` method after that.

**Comment by c9s** [comment]
@jeffreycahyono does it work for you?

**Comment by jeffreycahyono** [comment]
Hello Yo An Lin, 
I figure out the problem, The bug exists in ver 2.2.3 (which I used), after i switched to dev-master ( f5f7e46), the problem gone.

**Comment by c9s** [comment]
ok should I roll out a new release?

**Comment by jeffreycahyono** [comment]
Yes please, My test case passed if using the  dev-master ( f5f7e46)

**Comment by c9s** [comment]
2.2.4 is released.

**Comment by jeffreycahyono** [comment]
Thanks a lot for responding this issues. Problem solved. Continuous Option Parser run perfect now.
