### ISSUE TITLE
Arguments aren't consumed for "multiple" options

### ISSUE THREAD

**Issue by lillesvin** [c9s/GetOptionKit#37]
When defining a "single" option (e.g. `foo:=string`), that option's argument will be consumed and not returned with the remaining arguments from getArguments(), but a "multiple" option (e.g. `bar+=string`) does not consume its argument and leaves it with the rest of the arguments returned by getArguments().

```php
$specs = new \GetOptionKit\OptionCollection();
$specs->add('test1+=string', 'Test 1');
$specs->add('test2:=string', 'Test 2');

$parser = new \GetOptionKit\OptionParser($specs);

$result = $parser->parse(explode(' ', '--test1 opt1 --test2 opt2 arg1 arg2'));

$result->getArguments(); // => ["opt1", "arg1", "arg2"]
```

Ideally, at least to the best of my knowledge, the arguments to a "multiple" option should be consumed and removed from the list returned by getArguments() so only `["arg1", "arg2"]` would be returned in the above example.

**Comment by c9s** [comment]
This is fixed and tested in 5cb9af4..d581718

**Comment by c9s** [comment]
sorry for the delay

**Comment by c9s** [comment]
Please note that the parse method now expect the first argument in argv to be the program name, this is to make the parsing behaviour consistent with continuous parser.

```php
$result = $parser->parse(explode(' ', 'prog --test1 opt1 --test2 opt2 arg1 arg2'));
```

**Comment by lillesvin** [comment]
Nice. Thanks for fixing this! Looking forward to trying it out. :)
