### ISSUE TITLE
string is parsed as number

### ISSUE THREAD

**Issue by andreiaf** [c9s/GetOptionKit#40]
when option is set as `$specs->add('s|serial=string,'my string value')` and on command line it is invoked as say `$php sript.php -s="0001"`, the parameter is treated as number 1 instead of a string '0001' and exception is thrown while invoking ->parse(argv)
`$ Invalid value for -s, --serial. Requires a type String`

**Comment by c9s** [comment]
Hi !  did you find a way out?
