### ISSUE TITLE
isa('Number') is not worknig.

### ISSUE THREAD

**Issue by romaninsh** [c9s/GetOptionKit#44]
Documentation is inconsistent about 'number' vs 'Number': https://github.com/c9s/GetOptionKit/search?utf8=✓&q=isa

```
$specs->add('s|system', 'Select system by ID' )->isa('Number');
```

Orange-Dream:tools rw$ php importer.php -s 123
	-s, --system=<Number>
		Select system by ID

PHP Fatal error:  Uncaught GetOptionKit\InvalidOptionValue: Invalid value for -s, --system. Requires a type Number. in /Users/rw/Sites/smbo/old/vendor/corneltek/getoptionkit/src/Option.php:264
Stack trace:
#0 /Users/rw/Sites/smbo/old/vendor/corneltek/getoptionkit/src/Option.php(297): GetOptionKit\Option->_preprocessValue(true)
#1 /Users/rw/Sites/smbo/old/vendor/corneltek/getoptionkit/src/OptionParser.php(48): GetOptionKit\Option->setValue(true)
#2 /Users/rw/Sites/smbo/old/vendor/corneltek/getoptionkit/src/OptionParser.php(172): GetOptionKit\OptionParser->consumeOptionToken(Object(GetOptionKit\Option), Object(GetOptionKit\Argument), Object(GetOptionKit\Argument))
#3 /Users/rw/Sites/smbo/old/tools/importer.php(32): GetOptionKit\OptionParser->parse(Array)
#4 {main}
  thrown in /Users/rw/Sites/smbo/old/vendor/corneltek/getoptionkit/src/Option.php on line 264

Fatal error: Uncaught GetOptionKit\InvalidOptionValue: Invalid value for -s, --system. Requires a type Number. in /Users/rw/Sites/smbo/old/vendor/corneltek/getoptionkit/src/Option.php on line 264

GetOptionKit\InvalidOptionValue: Invalid value for -s, --system. Requires a type Number. in /Users/rw/Sites/smbo/old/vendor/corneltek/getoptionkit/src/Option.php on line 264

**Comment by c9s** [comment]
the option you defined is a flag

not an option with value, to define one option with value, please use the
follwoing spec

s|system:



Romans Malinovskis <notifications@github.com> 於 2016年7月12日 星期二寫道：

**Comment by c9s** [comment]
it doesnt matter on Number or number, the factory method will capitalize
the word

Romans Malinovskis <notifications@github.com> 於 2016年7月12日 星期二寫道：

**Comment by c9s** [comment]
the reason: flag requires value to be boolean, however boolean is not a number.

**Comment by romaninsh** [comment]
still unclear, but i leave it to you.
