### ISSUE TITLE
No documentation on "normal" arguments

### ISSUE THREAD

**Issue by romaninsh** [c9s/GetOptionKit#45]
Read-me mentions ability to mix with normal arguments here:

https://github.com/c9s/GetOptionKit#supported-option-formats

However I can't find a way to implement this:

    myapp [ -s <system_id> ] file.txt

I was expecting than parser would remove all arguments from parameter leaving normal arguments inside, but it's not happening.

**Comment by c9s** [comment]
you dont have to define normal argument,

since your -s requires a system id, the option must be defined with
"require value".

Romans Malinovskis <notifications@github.com> 於 2016年7月12日 星期二寫道：

**Comment by romaninsh** [comment]
That's fine but how do i get 'file.txt' ?

**Comment by c9s** [comment]
for your case:

```
$specs->add('f|foo:', 'option requires a value.' )
    ->isa('String');
....
$result = $parser->parse( $argv );
$args = $result->getArguments();

```

**Comment by romaninsh** [comment]
Perfect. That's exactly the piece missing from documentation.  Is there a place where to ask further questions btw?

**Comment by c9s** [comment]
Yes, just ask under this issue, it's fine.

**Comment by romaninsh** [comment]
i noticed it now in the main example of Readme, but initially missing and went in circles.

**Comment by c9s** [comment]
yeah I just updated the readme for the API.
