### ISSUE TITLE
unclear how to actually get value

### ISSUE THREAD

**Issue by romaninsh** [c9s/GetOptionKit#46]
Coming from a [getopt](http://php.net/manual/en/function.getopt.php) I expect that calling this:

``` bash
shell> php example.php -fvalue -h
```

and using parse() would give me something like:

``` php
array(2) {
  ["f"]=>
  string(5) "value"
  ["h"]=>
  bool(false)
}
```

However parse() responds with spec definitions strings:

```
$result = $parser->parse($argv);
echo 's is '.$result['f']."\n";
```

While it's handy for a demo, it's unclear how to actually get the value. My final working snippet looks like this:

```
$specs = new \GetOptionKit\OptionCollection;
$specs->add('f:', 'value of f' );
$parser = new \GetOptionKit\OptionParser($specs);
$result = $parser->parse($argv)->toArray();
echo 'f is '.$result['f']."\n";
```

but it took some poking in the code to arrive at this.

**Comment by c9s** [comment]
sounds like a bug?

**Comment by c9s** [comment]
```
        $this->specs->add('f:' , 'file');
        $result = $this->parser->parse(array('a', '-f', 'aaa'));
        $this->assertEquals('aaa',$result['f']->getValue());
```

**Comment by c9s** [comment]
The option result returns Option object, you need to call "getValue" on it.

**Comment by c9s** [comment]
But $result->f should work for you

$result['f'] is used to get the raw object.
