### ISSUE TITLE
Validator isn't triggered

### ISSUE THREAD

**Issue by ErikBooij** [c9s/GetOptionKit#49]
Hi! I really like the library you've created for parsing CLI arguments, but I'm running into an issue. I'm probably just using it wrong, but maybe you can clarify.

I'm trying to add a validator to an option, to make sure the option is an existing and readable file. I was assuming it would work something like this:

```php
$specs
    ->add('c|candidates:', 'Candidates file')
    ->validator(function($option) {
        return file_exists($option) && is_readable($option);
    });
```

But it doesn't. The validate function is used nowhere in the entire library (according to PHPStorm), so I figured I needed to trigger it myself, but doing this seems unnecessarily complicated:

```php
$option->validate($option->value)
```

If it should actually automatically validate, I'll be more than happy to create a PR and change it, but I wanted to check first if this is not just the intended behaviour.

**Comment by c9s** [comment]
This seems like a bug, yes, it should be automatically validated.

**Comment by ErikBooij** [comment]
Thanks for your quick reply, I'll see if I can work out a fix and create a PR.

**Comment by c9s** [comment]
Thanks!

**Comment by ErikBooij** [comment]
Fixed in https://github.com/c9s/GetOptionKit/pull/50
