### ISSUE TITLE
Support for PHP 8.1

### ISSUE THREAD

**Issue by Sweetchuck** [c9s/GetOptionKit#59]
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /.../corneltek/getoptionkit/src/Option.php on line 130

https://github.com/phpbrew/phpbrew/issues/1245

**Comment by peter279k** [comment]
It should be fixed in the [latest PR](https://github.com/c9s/GetOptionKit/pull/62).
